version: "4.14"
services:
  postgres:
        image: postgres:latest
        container_name: postgres
        ports:
         - 5432:5432
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server